### ISSUE TITLE
Priest T2/Devout (DPS) 6 set

### ISSUE THREAD

**Issue by killersoxfan** [Duskhaven/Bug-Reports#1056]
![image](https://user-images.githubusercontent.com/128938821/232931158-bcfc1588-76d6-4c22-b996-a525978156e2.png)

The 6 set bonus, all but
Fist of the Tiger doing 60% damage as DoT and Crit + Armor pen: Not working

Still working on 8 set to test if it's set bonus is working. Would be great if somebody else could check this for me.

**Comment by Duskhaven** [comment]
5% crit works after restart

**Comment by killersoxfan** [comment]
Still not working for me, yet. I have updated patch as well.

**Comment by Duskhaven** [comment]
The Fist of the Tiger burn now works, but you have to use trash kick first. The crit chance and armor ignore has been exchanged for a spell damage taken debuff and armor reduction.

**Comment by Duskhaven** [comment]
Fixed (Lightform one requires a restart)

**Comment by killersoxfan** [comment]
Ty sir!

**Comment by killersoxfan** [comment]
broken again

**Comment by retclasslead** [comment]
> broken again

Confirming it is still broken.
It was working right before the zg hc update restart and then broke after it.
